"""Initial CropGuard schema."""

from alembic import op
import sqlalchemy as sa


revision = "20261003_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    user_role = sa.Enum(
        "FARMER",
        "EXTENSION_OFFICER",
        "ADMIN",
        name="user_role",
    )

    diagnosis_status = sa.Enum(
        "UPLOADED",
        "ANALYZED",
        "FAILED",
        name="diagnosis_status",
    )

    op.create_table(
        "users",
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=False,
        ),
        sa.Column(
            "full_name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "role",
            user_role,
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id",
        ),
        sa.UniqueConstraint(
            "email",
            name="uq_users_email",
        ),
    )

    op.create_index(
        "ix_users_email",
        "users",
        ["email"],
        unique=False,
    )

    op.create_table(
        "refresh_tokens",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "jti",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_refresh_tokens_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
        ),
        sa.UniqueConstraint(
            "jti",
            name="uq_refresh_tokens_jti",
        ),
    )

    op.create_index(
        "ix_refresh_tokens_user_id",
        "refresh_tokens",
        ["user_id"],
        unique=False,
    )

    op.create_index(
        "ix_refresh_tokens_jti",
        "refresh_tokens",
        ["jti"],
        unique=False,
    )

    op.create_table(
        "farms",
        sa.Column(
            "owner_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "village",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "district",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "state",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "country",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "latitude",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "longitude",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name="fk_farms_owner_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
        ),
    )

    op.create_index(
        "ix_farms_owner_id",
        "farms",
        ["owner_id"],
        unique=False,
    )

    op.create_table(
        "fields",
        sa.Column(
            "farm_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "crop_name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "variety",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "area_acres",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "sowing_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
            name="fk_fields_farm_id_farms",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
        ),
    )

    op.create_index(
        "ix_fields_farm_id",
        "fields",
        ["farm_id"],
        unique=False,
    )

    op.create_table(
        "diagnoses",
        sa.Column(
            "field_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "image_path",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "original_filename",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "status",
            diagnosis_status,
            nullable=False,
        ),
        sa.Column(
            "predicted_label",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "severity",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "advisory",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
            name="fk_diagnoses_field_id_fields",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
        ),
    )

    op.create_index(
        "ix_diagnoses_field_id",
        "diagnoses",
        ["field_id"],
        unique=False,
    )

    op.create_table(
        "alerts",
        sa.Column(
            "field_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=180),
            nullable=False,
        ),
        sa.Column(
            "message",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "risk_level",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "is_read",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
            name="fk_alerts_field_id_fields",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
        ),
    )

    op.create_index(
        "ix_alerts_field_id",
        "alerts",
        ["field_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_alerts_field_id",
        table_name="alerts",
    )
    op.drop_table(
        "alerts",
    )

    op.drop_index(
        "ix_diagnoses_field_id",
        table_name="diagnoses",
    )
    op.drop_table(
        "diagnoses",
    )

    op.drop_index(
        "ix_fields_farm_id",
        table_name="fields",
    )
    op.drop_table(
        "fields",
    )

    op.drop_index(
        "ix_farms_owner_id",
        table_name="farms",
    )
    op.drop_table(
        "farms",
    )

    op.drop_index(
        "ix_refresh_tokens_jti",
        table_name="refresh_tokens",
    )
    op.drop_index(
        "ix_refresh_tokens_user_id",
        table_name="refresh_tokens",
    )
    op.drop_table(
        "refresh_tokens",
    )

    op.drop_index(
        "ix_users_email",
        table_name="users",
    )
    op.drop_table(
        "users",
    )